{{- if and (not .Values.database.external) (eq .Values.database.type "mysql") }}
apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "databunkerpro.fullname" . }}-mysql
  labels:
    {{- include "databunkerpro.labels" . | nindent 4 }}
    app.kubernetes.io/component: mysql
spec:
  replicas: 1
  selector:
    matchLabels:
      {{- include "databunkerpro.selectorLabels" . | nindent 6 }}
      app.kubernetes.io/component: mysql
  template:
    metadata:
      labels:
        {{- include "databunkerpro.selectorLabels" . | nindent 8 }}
        app.kubernetes.io/component: mysql
    spec:
      containers:
        - name: mysql
          image: "{{ .Values.database.internal.mysql.image.repository }}:{{ .Values.database.internal.mysql.image.tag }}"
          ports:
            - name: mysql
              containerPort: 3306
              protocol: TCP
          env:
            - name: MYSQL_DATABASE
              value: {{ .Values.database.internal.mysql.auth.database | quote }}
            - name: MYSQL_USER
              value: {{ .Values.database.internal.mysql.auth.username | quote }}
            - name: MYSQL_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: {{ include "databunkerpro.fullname" . }}-db
                  key: password
            - name: MYSQL_ROOT_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: {{ include "databunkerpro.fullname" . }}-db
                  key: root-password
          volumeMounts:
            - name: data
              mountPath: /var/lib/mysql
          resources:
            {{- toYaml .Values.database.internal.mysql.resources | nindent 12 }}
      volumes:
        - name: data
          {{- if .Values.database.internal.mysql.persistence.enabled }}
          persistentVolumeClaim:
            claimName: {{ include "databunkerpro.fullname" . }}-mysql
          {{- else }}
          emptyDir: {}
          {{- end }}
---
apiVersion: v1
kind: Service
metadata:
  name: {{ include "databunkerpro.fullname" . }}-mysql
  labels:
    {{- include "databunkerpro.labels" . | nindent 4 }}
    app.kubernetes.io/component: mysql
spec:
  type: ClusterIP
  ports:
    - port: 3306
      targetPort: mysql
      protocol: TCP
      name: mysql
  selector:
    {{- include "databunkerpro.selectorLabels" . | nindent 4 }}
    app.kubernetes.io/component: mysql
{{- if .Values.database.internal.mysql.persistence.enabled }}
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: {{ include "databunkerpro.fullname" . }}-mysql
  labels:
    {{- include "databunkerpro.labels" . | nindent 4 }}
    app.kubernetes.io/component: mysql
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: {{ .Values.database.internal.mysql.persistence.size }}
{{- end }}
{{- end }} 