apiVersion: v1
kind: Secret
metadata:
  name: {{ include "databunkerpro.fullname" . }}-db
  labels:
    {{- include "databunkerpro.labels" . | nindent 4 }}
type: Opaque
data:
  {{- if and (not .Values.database.external) (eq .Values.database.type "mysql") (.Values.database.internal.mysql.enabled) }}
  password: {{ .Values.database.internal.mysql.auth.password | default (randAlphaNum 32) | b64enc | quote }}
  root-password: {{ .Values.database.internal.mysql.auth.rootPassword | default (randAlphaNum 32) | b64enc | quote }}
  {{- else if and (not .Values.database.external) (eq .Values.database.type "postgresql") }}
  password: {{ .Values.database.internal.postgresql.auth.password | default (randAlphaNum 32) | b64enc | quote }}
  {{- else if .Values.database.external }}
  password: {{ .Values.database.externalConfig.password | required "External database password is required when database.external=true" | b64enc | quote }}
  {{- end }}
