apiVersion: v1
kind: Secret
metadata:
  name: {{ include "databunkerpro.fullname" . }}-wrapping-key
  labels:
    {{- include "databunkerpro.labels" . | nindent 4 }}
type: Opaque
data:
  wrapping-key: {{ .Values.config.wrappingKey | default (randAlphaNum 32) | b64enc | quote }}