apiVersion: v1
kind: Secret
metadata:
  name: {{ include "databunkerpro.fullname" . }}-wrapping-key
  labels:
    {{- include "databunkerpro.labels" . | nindent 4 }}
type: Opaque
data:
  {{- if .Values.config.wrappingKey }}
    {{- $wrappingKey = .config.wrappingKey | b64enc | quote }}
  {{- else }}
    {{- $wrappingKey = substr 1 49 (printf "%x%x%x%x%x%x" (int64 (randNumeric 18)) (int64 (randNumeric 18)) (int64 (randNumeric 18)) (int64 (randNumeric 18)) (int64 (randNumeric 18)) (int64 (randNumeric 18)) ) | b64enc | quote }}
  {{- end }}
  wrapping-key: {{ $wrappingKey }}
