{{- if and (not .Values.database.external) (eq .Values.database.type "mysql") }}
apiVersion: v1
kind: Secret
metadata:
  name: {{ include "databunkerpro.fullname" . }}-db
  labels:
    {{- include "databunkerpro.labels" . | nindent 4 }}
type: Opaque
data:
  password: {{ .Values.database.internal.mysql.auth.password | default (randAlphaNum 32) | b64enc | quote }}
  root-password: {{ .Values.database.internal.mysql.auth.rootPassword | default (randAlphaNum 32) | b64enc | quote }}
{{- end }}
{{- if and (not .Values.database.external) (eq .Values.database.type "postgresql") }}
apiVersion: v1
kind: Secret
metadata:
  name: {{ include "databunkerpro.fullname" . }}-db
  labels:
    {{- include "databunkerpro.labels" . | nindent 4 }}
type: Opaque
data:
  password: {{ .Values.database.internal.postgresql.auth.password | default (randAlphaNum 32) | b64enc | quote }}
{{- end }} 