apiVersion: v1
kind: Service
metadata:
  name: {{ include "databunkerpro.fullname" . }}
  labels:
    {{- include "databunkerpro.labels" . | nindent 4 }}
spec:
  type: {{ .Values.service.type }}
  ports:
    - port: {{ .Values.service.port }}
      targetPort: {{ .Values.config.databunker.port }}
      protocol: TCP
      {{- if .Values.ssl.enabled }}
      name: https
      {{ else }}
      name: http
      {{- end }}
  selector:
    app.kubernetes.io/name: {{ include "databunkerpro.name" . }}
    app.kubernetes.io/instance: {{ .Release.Name }}
    app.kubernetes.io/component: databunkerpro