{{- if and .Values.ssl.enabled .Values.ssl.generateSelfSigned.enabled }}
apiVersion: v1
kind: ServiceAccount
metadata:
  name: {{ include "databunkerpro.fullname" . }}-sa-ssl-certs
  labels:
    {{- include "databunkerpro.labels" . | nindent 4 }}
  annotations:
    "helm.sh/hook": pre-install,pre-upgrade
    "helm.sh/hook-weight": "-10"
    "helm.sh/hook-delete-policy": before-hook-creation
---
apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  name: {{ include "databunkerpro.fullname" . }}-role-ssl-certs
  labels:
    {{- include "databunkerpro.labels" . | nindent 4 }}
  annotations:
    "helm.sh/hook": pre-install,pre-upgrade
    "helm.sh/hook-weight": "-9"
    "helm.sh/hook-delete-policy": before-hook-creation
rules:
  - apiGroups: [""]
    resources: ["secrets"]
    verbs: ["get", "create", "update", "patch"]
    resourceNames: ["{{ include "databunkerpro.fullname" . }}-tls"]
---
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: {{ include "databunkerpro.fullname" . }}-rolebinding-ssl-certs
  labels:
    {{- include "databunkerpro.labels" . | nindent 4 }}
  annotations:
    "helm.sh/hook": pre-install,pre-upgrade
    "helm.sh/hook-weight": "-8"
    "helm.sh/hook-delete-policy": before-hook-creation
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: Role
  name: {{ include "databunkerpro.fullname" . }}-role-ssl-certs
subjects:
  - kind: ServiceAccount
    name: {{ include "databunkerpro.fullname" . }}-sa-ssl-certs
    namespace: {{ .Release.Namespace }}
{{- end }}
