apiVersion: v1
kind: Service
metadata:
  name: {{ include "databunkerpro.fullname" . }}
  labels:
    {{- include "databunkerpro.labels" . | nindent 4 }}
spec:
  type: {{ .Values.service.type }}
  ports:
    - port: {{ .Values.service.port }}
      targetPort: {{ .Values.config.databunker.port }}
      protocol: TCP
      name: http
  selector:
    {{- include "databunkerpro.selectorLabels" . | nindent 4 }} 