services:
  mysql:
    #image: mysql/mysql-server
    image: percona
    deploy:
      resources:
        limits:
          memory: 16G
    env_file:
      - .env/mysql-root.env
      - .env/mysql.env
    restart: unless-stopped
    volumes:
      - ./data:/var/lib/mysql
    #command: --max_connections=2048 --innodb_buffer_pool_size=12G --innodb_buffer_pool_instances=8 --innodb_flush_log_at_trx_commit=2 --innodb_flush_method=O_DIRECT --innodb_file_per_table=ON --innodb_log_buffer_size=128M --table_open_cache=4096 --tmp_table_size=256M --max_heap_table_size=256M --tmp_table_size=64M --max_heap_table_size=64M --join_buffer_size=64M --sort_buffer_size=64M --read_rnd_buffer_size=16M
  redis:
    image: redis
    restart: unless-stopped
    ports:
      - "127.0.0.1:6379:6379"
  databunkerpro:
    image: registry.databunker.org/databunkerpro:latest
    restart: unless-stopped
    env_file:
      - .env/databunker.env
    volumes:
      - ./databunker.yaml:/databunker/conf/databunker.yaml
      - ./certs:/databunker/certs
    #entrypoint: /databunker/bin/databunker -db databunkerdb -conf /databunker/conf/databunker.yaml
    entrypoint: /bin/sh
    command: -c "/databunker/bin/databunkerpro -db databunkerdb -conf /databunker/conf/databunker.yaml"
    depends_on:
      - mysql
    ports:
      - 3000:3000
