name: Publish Helm Chart

on:
  workflow_dispatch:
  push:
    branches:
      - master
    paths:
      - 'helm/**'
      - '.github/workflows/publish-helm-chart.yml'
  release:
    types: [published]

jobs:
  publish:
    runs-on: ubuntu-latest
    permissions:
      contents: read
      packages: write
      pages: write
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Set up Helm
        uses: azure/setup-helm@v3
        with:
          version: v3.12.0

      - name: Create Release Package
        run: |
          cd helm/databunkerpro
          helm package .
          mv databunkerpro-*.tgz ../../

      - name: Create Helm Repository
        run: |
          # Create a temporary directory for the repository
          mkdir -p helm-repo
          # Copy the chart package
          cp databunkerpro-*.tgz helm-repo/
          # Generate the index file
          helm repo index helm-repo --url https://securitybunker.github.io/databunkerpro-setup

      - name: Deploy to GitHub Pages
        uses: peaceiris/actions-gh-pages@v3
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ./helm-repo
          publish_branch: gh-pages
          commit_message: "Update Helm repository index"